### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by Thirstums** [Tectato/Fire_Rekindled#1]
# Hello @Tectato 

I recently came across your Fire_Rekindled Recourcepack (looking for inspo to make my own) and I've tried to create some normal maps for minecrafts Vanilla Textures.. but for some reason can't get it to work. Could I maybe ask you for some Help? If so, 

My discord would be @Thirstums or just Thirstums. Not sure how the new tags work.

I am writing this here because it's the only way I could find to contact you, lol

Kind regards
Thirsty

**Comment by Tectato** [comment]
Sent a request on discord
